name: iOS Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '13.x'

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build and Test
      run: xcodebuild -workspace contalizze.xcworkspace -scheme contalizze clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
